version: "3.8"
services:
  scrum-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrumpoker
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
